### ISSUE TITLE
Fix popular `nixos-install` issue

### ISSUE THREAD

**Issue by BentonEdmondson** [samuela/nixos-up#11]
I just had an issue with `nixos-install` and it seems to be popular: https://github.com/NixOS/nixpkgs/issues/126141, [reddit/NixOS#o0gil2](https://www.reddit.com/r/NixOS/comments/o0gil2/does_anyone_know_how_to_fix_this_error/). The solution here worked: https://github.com/NixOS/nixpkgs/issues/126141#issuecomment-861720372.

To reproduce I just fresh installed using `nixos-up` and the issue appeared.

Assuming you reproduce the issue and solution, you should add the fix to this script so that new users aren't turned away by a first impression like this.

**Comment by samuela** [comment]
Thanks for the pointer! Works like a charm for me!
