### ISSUE TITLE
Config regex is missing `lib` which causes error "undefined variable 'home-manager'"

### ISSUE THREAD

**Issue by ChrisIgel** [samuela/nixos-up#20]
With the current version of the NixOS image (`nixos-minimal-24.05.4469.6e99f2a27d60-x86_64-linux`) the script does not work any more and errors with:
![image](https://github.com/user-attachments/assets/eefae4a4-3106-46d8-be70-6e27477d6957)

These lines
https://github.com/samuela/nixos-up/blob/619ecd95569b3520b600199134100138877fbce6/nixos-up.py#L218-L219

Should probably now look like this
```python
config = re.sub(r"{ config, lib, pkgs, \.\.\. }:\s+{", f"""\ 
{{ config, lib, pkgs, ...}}: 
```

**Comment by samuela** [comment]
mmm, i guess they've changed the default `configuration.nix`. would be a good first PR for anyone interested!

**Comment by samuela** [comment]
Why does this cause an issue with home-manager though?

**Comment by ChrisIgel** [comment]
> Owner

Because the following lines would introduce the `home-manager` variable but the code snippet does not get injected in to the `configuration.nix` because the regex does not match any longer:
https://github.com/samuela/nixos-up/blob/619ecd95569b3520b600199134100138877fbce6/nixos-up.py#L218-L230

This on the other hand matches which is why `${home-manager}` cannot be resolved:
https://github.com/samuela/nixos-up/blob/619ecd95569b3520b600199134100138877fbce6/nixos-up.py#L231

**Comment by samuela** [comment]
ahhh that makes sense! i had forgotten about that
