### ISSUE TITLE
Suggestion: move passwordFile to /etc/nixos/

### ISSUE THREAD

**Issue by ryantm** [samuela/nixos-up#3]
https://github.com/samuela/nixos-up/blob/56591a73d11c3b991aaa1acfc605478ef5e3a6b3/nixos-up.ml#L245

I think it might be easier for people to find their password file if it is in the same directory as `configuration.nix`.

**Comment by samuela** [comment]
I think this mainly comes down to a matter of choice. I was actually thinking of creating a `passwordFiles` directory with entries for each username but that seemed like overkill. I had this notion that `/etc/nixos` was sort of spec'd for things that have meaning to NixOS like `configuration.nix`, `hardware-configuration.nix`, etc. But I suppose nothing prevents putting user created files there.

I don't have a strong opinion on it one way or the other. I'd be happy to take a PR for it.

**Comment by ryantm** [comment]
Yeah, I don't have too strong of an opinion either. So I'll close this and we can wait to see if we can any other user feedback.

**Comment by BentonEdmondson** [comment]
For the record and as long as you're interested in more feedback, I do prefer it being in `/etc/nixos/`. That way I can get every bit of system configuration within that one directory. But as you guys say, it's a technically inconsequential decision.
