### ISSUE TITLE
device/model also not reliable

### ISSUE THREAD

**Issue by ryantm** [samuela/nixos-up#6]
I recently made a QEMU/KVM VM that had a glusterfs-backed disk using the native glusterfs filesystem connection and it has a device/vendor but no device/model, so the installer failed:

![image](https://user-images.githubusercontent.com/4804/117210806-046afd00-adad-11eb-9a69-3c41ccc75025.png)

**Comment by samuela** [comment]
Very interesting... I really wish there was a proper spec for these linux virtual file systems. Would falling back to `device/vendor` if `device/model` is not present be sufficient for your use case?

**Comment by ryantm** [comment]
Maybe it should just display both those values if it finds them and otherwise not fail?

**Comment by samuela** [comment]
Oh, right. I forgot it was already fetching vendor and model... Should be fixed in https://github.com/samuela/nixos-up/commit/5641889e05c673d92cb43dd84eac38b75445ff8d. Let me know if not!

**Comment by ryantm** [comment]
Pleased to report this is fixed now! Thank you.
