### ISSUE TITLE
mkfs.fat -F 32 -n boot /dev/nvme0n11 - No such file or directory

### ISSUE THREAD

**Issue by BentonEdmondson** [samuela/nixos-up#7]
Hi. This is a great tool. I'm getting an error. I think it is occurring [here](https://github.com/samuela/nixos-up/blob/main/nixos-up.ml#L198). The drive I am installing NixOS onto is `/dev/nvme0n1`.

Here's the ending output:
```
>>> parted /dev/nvme0n1 -- mkpart primary 512 MiB 100%
Information: You may need to update /etc/fstab.

>>> mkfs.fat -F 32 -n boot /dev/nvme0n11
mkfs.fat 4.1 (2017-01-24)
mkfs.fat:  warning - lowercase labels might not work properly with DOS or Windows
mkfs.fat: unable to open /dev/nvme0n11: No such file or directory
Exception: CommandFailure "mkfs.fat -F 32 -n boot /dev/nvme0n11".
Called from unknown location
Called from file "toplevel/toploop.ml", line 212, characters 17-21
```

I know hardly anything about what's going on here. Maybe you have to go from `/dev/nvme0n1` to `/dev/nvme0n2` and `/dev/nvme0n3` instead of to `/dev/nvme0n11` and `/dev/nvme0n12`?

Thanks in advance

**Comment by samuela** [comment]
Hmm, that's interesting... So it looks like you're on an EFI/UEFI system? `/dev/nvme0n11` generally means `/dev/<disk=nvme0n1><partition=1>`. Unfortunately, I don't have an nvme machine to test on. Have you had success with the manual install process? If so, would you mind posting the steps that work?

Would you mind posting the output of `lsblk` after nixos-up fails?

**Comment by BentonEdmondson** [comment]
I haven't ever done a manual NixOS install. This is EFI/UEFI.

The `lsblk` returned (among other things):
```
nvme0n1
   nvme0n1p1
   nvme0n1p2
```
(tell me if you need more)

I found this that corroborates that we need `/dev/nvme0n1p1`: https://github.com/rancher/os/issues/742#issuecomment-201998143.

If you make the edit on a new branch I can pull it down and test it for you before you put it in main.

**Comment by samuela** [comment]
Ahhhh I see... Ok lemme try putting together a fix!

**Comment by samuela** [comment]
Ok, I think I fixed it in https://github.com/samuela/nixos-up/commit/ff6f1e05f258f386f892c3e191a7bc49fa3e5793... but please give it a shot and let me know if it works for you!

**Comment by BentonEdmondson** [comment]
Alright I'll give it a try. Hopefully it doesn't brick my system haha.

**Comment by BentonEdmondson** [comment]
It's working! Thank you! See https://github.com/samuela/nixos-up/issues/8, though. I had one solvable hiccup along the way.
