### ISSUE TITLE
Does not work with NixOS 21.05 minimal installer on VMware Fusion

### ISSUE THREAD

**Issue by gcv** [samuela/nixos-up#9]
I tried using nixos-up to install NixOS 21.05 on a VM on VMware Fusion 11.5.7. It blows up as shown in the attached screenshot. The installer ISO is from here: https://channels.nixos.org/nixos-21.05/latest-nixos-minimal-x86_64-linux.iso (linked on this page: https://nixos.org/download.html#nixos-iso).

<img width="809" alt="Screen Shot 2021-06-05 at 11 32 16" src="https://user-images.githubusercontent.com/10327/120901852-14673e00-c5f2-11eb-845f-2ad18ec268ef.png">

**Comment by samuela** [comment]
Hmm weird... That actually looks like it may be an issue with nixos-install. I'll give it a shot today and see what happens.

**Comment by samuela** [comment]
Ok, I can reproduce this in VirtualBox as well. I'm gonna dig through the release notes to see if anything's changed. Barring any big surprises there I think this is a `nixos-install` issue.

**Comment by gcv** [comment]
Thank you! I should probably try again with an earlier release ISO.

**Comment by samuela** [comment]
This isn't the prettiest fix in the world, but you can 
1. Run nixos-up, let the installer fail.
2. Edit `/mnt/etc/nixos/configuration.nix` and comment out the line that says `environment.systemPackages = ...`.
3. Run `sudo nixos-install --no-root-passwd`. Once that succeeds, you're all set to go!

Granted, this sucks but it's a workaround until https://github.com/NixOS/nixpkgs/issues/125860 gets resolved.

**Comment by gcv** [comment]
Excellent, that worked. Thank you so much for looking into this so quickly, and for opening the upstream ticket.

**Comment by samuela** [comment]
Yeah, no problem! Glad to hear it worked for you!
